### ISSUE TITLE
Raze not detecting proc-macro deps?

### ISSUE THREAD

**Issue by camertron** [google/cargo-raze#181]
Hey everyone,

Bear with me here, I'm very new to both Rust and Bazel.

I'm running into a strange issue where raze seems to generate an invalid BUILD file and causes this error when I attempt to run `bazel build //rust/diff`:

```
INFO: Invocation ID: 72d09659-161d-4900-8c3b-034072d7d04d
ERROR: /root/.cache/bazel/_bazel_root/933c2f549343e099e3a6911b282cb71c/external/raze__markup5ever__0_10_0/BUILD.bazel:30:1: in rust_binary rule @raze__markup5ever__0_10_0//:markup5ever_build_script_script_:
Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/933c2f549343e099e3a6911b282cb71c/external/raze__markup5ever__0_10_0/BUILD.bazel", line 30
		rust_binary(name = 'markup5ever_build_script_script_')
	File "/root/.cache/bazel/_bazel_root/933c2f549343e099e3a6911b282cb71c/external/io_bazel_rules_rust/rust/private/rust.bzl", line 169, in _rust_binary_impl
		rustc_compile_action(ctx = ctx, <2 more arguments>)
	File "/root/.cache/bazel/_bazel_root/933c2f549343e099e3a6911b282cb71c/external/io_bazel_rules_rust/rust/private/rustc.bzl", line 442, in rustc_compile_action
		collect_deps(ctx.label, <4 more arguments>)
	File "/root/.cache/bazel/_bazel_root/933c2f549343e099e3a6911b282cb71c/external/io_bazel_rules_rust/rust/private/rustc.bzl", line 125, in collect_deps
		fail(<1 more arguments>)
@raze__markup5ever__0_10_0//:markup5ever_build_script_script_ listed @raze__serde_derive__1_0_114//:serde_derive in its deps, but it is a proc-macro. It should instead be in the bazel property proc_macro_deps.
ERROR: Analysis of target '//rust/diff:diff' failed; build aborted: Analysis of target '@raze__markup5ever__0_10_0//:markup5ever_build_script_script_' failed; build aborted
INFO: Elapsed time: 2.092s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (50 packages loaded, 1020 targets configured)
```

Indeed, the relevant part of the BUILD file in question shows this:

```
cargo_build_script(
    name = "markup5ever_build_script",
    srcs = glob(["**/*.rs"]),
    crate_root = "build.rs",
    edition = "2018",
    deps = [
        "@raze__phf_codegen__0_8_0//:phf_codegen",
        "@raze__serde__1_0_114//:serde",
        "@raze__serde_derive__1_0_114//:serde_derive",
        "@raze__serde_json__1_0_56//:serde_json",
        "@raze__string_cache_codegen__0_5_1//:string_cache_codegen",
    ],
    rustc_flags = [
        "--cap-lints=allow",
    ],
    crate_features = [
    ],
    data = glob(["**"]),
    tags = ["cargo-raze"],
    version = "0.10.0",
    visibility = ["//visibility:private"],
)
```

If I move `@raze__serde_derive__1_0_114//:serde_derive` into the `proc_macro_deps` section, the build runs without issue.

Is raze just not detecting that `serde_derive` is a proc-macro crate?

**Comment by dfreese** [comment]
What version of cargo-raze are you using?  Which commit of rules_rust?

**Comment by camertron** [comment]
@dfreese ah sorry, here we go:

cargo-raze: v0.3.6
rules_rust: f41a008d3e36e70b9deba9e4ed6cd914e8f36a49 (master as of yesterday)

**Comment by dfreese** [comment]
Ahh, yeah, that's a bug.  Looks like I missed that in the combination of #164 and #166.  I'll take a look at that soon.

@illicitonion, just a heads up.

**Comment by dfreese** [comment]
#182 should handle this, but I haven't had a chance to add some unit tests to that yet.

**Comment by camertron** [comment]
Awesome, thanks @dfreese :) Any chance you could publish a new crate as well?

**Comment by dfreese** [comment]
@camertron, yep, #182 is in v0.3.8
